name: Minify and Update Script

on:
  push:
    branches:
      - main

jobs:
  minify-and-update:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Minify the core/code.js
    - name: Install terser (JS minifier)
      run: |
        npm install terser -g

    - name: Minify code.js
      run: |
        terser core/code.js -o core/code.min.js --compress --mangle
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add core/code.min.js
        git commit -m "Minified core/code.js to core/code.min.js"
        git push origin main

    # Create and update the new userscript file
    - name: Update userscript-template.js
      run: |
        # Create a temporary file
        tmp_file=$(mktemp)

        # Copy userscript-template.js to a temporary file
        cp core/userscript-template.js "$tmp_file"

        # Replace the version number in the temporary file
        version=$(grep -oP '(?<=CONST version =")[^"]*' core/code.min.js)
        sed -i 's|^// @version .*|// @version '"$version"'|' "$tmp_file"

        # Replace line 15 with content of core/code.min.js
        minified_content=$(< core/code.min.js)
        sed -i '15s|.*|'"$minified_content"'|' "$tmp_file"

        # Move the temporary file to the final file location
        mv "$tmp_file" bm-toolkit-desktop.min.js

        # Add, commit, and push the updated bm-toolkit-desktop.min.js
        git add bm-toolkit-desktop.min.js
        git commit -m "Updated bm-toolkit-desktop.min.js with minified code and version $version"
        git push origin main
