name: Minify and Update

on:
  push:
    branches:
      - '*'  # Triggers on push to any branch
  pull_request:
    branches:
      - '*'  # Triggers on pull requests for any branch

jobs:
  minify-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'  # Adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Minify JS
      run: npx uglify-js code.js --compress --mangle --output code.min.js --comments false

    - name: Replace Line 16 in bm-toolkit-desktop.min.js with contents of code.min.js
      run: |
        if [ -s code.min.js ]; then
          awk 'NR==16 {while ((getline line < "code.min.js") > 0) print line; next} 1' bm-toolkit-desktop.min.js > temp.js
          mv temp.js bm-toolkit-desktop.min.js
        else
          echo "code.min.js is empty. No replacement done."
        fi
    
    - name: Update @version in bm-toolkit-desktop.min.js to CONST version
      run: |
        version=$(awk -F'"' '/const version/ {print $2}' code.js)
        awk -v version="$version" 'NR==4 {sub(/\/\/ @version .*/, "// @version " version)} {print}' bm-toolkit-desktop.min.js > temp.js
        mv temp.js bm-toolkit-desktop.min.js

      
    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add code.min.js bm-toolkit-desktop.min.js
        git commit -m "Minify JS and Update Versions"
        git push
