name: Minify and Update

on:
  push:
    branches:
      - '*'  # Triggers on push to any branch
  pull_request:
    branches:
      - '*'  # Triggers on pull requests for any branch

jobs:
  minify-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'  # Adjust the Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Minify JS
      run: npx uglify-js code.js -o code.min.js

    - name: Replace Line 15 in bm-toolkit-desktop.min.js with contents of code.min.js
      run: |
        # Read the content of code.min.js into a variable
        new_content=$(<code.min.js)
        
        # Escape special characters for safe replacement
        escaped_content=$(printf '%s\n' "$new_content" | sed -e 's/[]\/$*.^[]/\\&/g')

        # Replace line 15 in bm-toolkit-desktop.min.js
        sed "15s|.*|$escaped_content|" bm-toolkit-desktop.min.js > bm-toolkit-desktop.tmp
        mv bm-toolkit-desktop.tmp bm-toolkit-desktop.min.js

    
    - name: Update @version in bm-toolkit-desktop.min.js to CONST version
      run: |
        version=$(grep -oP 'const version = "\K[^"]+' code.js)
        sed -i "4s|// @version [0-9]*\(\.[0-9]*\)\?|// @version $version|" bm-toolkit-desktop.min.js
      
    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add code.min.js bm-toolkit-desktop.min.js
        git commit -m "Minify JS and Update Versions"
        git push
